version: "3"
services:
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=front
    depends_on:
      - "front"
      - "back"
  front:
    image: todofrontend
    depends_on:
      - "back"
    environment:
      - REACT_APP_API_HOST=back
    ports:
      - 3000:3000
  back: 
    image: todobackend
    ports:
      - 3001:3001
